(function(){
  const state={clients:[],referrals:[],ready:false,range:'all'};
  const day=86400000;
  const iso=d=>d?new Date(d+'T12:00:00'):null;
  const fmt=d=>d?new Intl.DateTimeFormat('en-IE',{day:'numeric',month:'short',year:'numeric'}).format(iso(d)):'Not set';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function leadFor(c){return getLeads().find(l=>String(l.id)===String(c.lead_id))||{};}
  function calc(c){
    const now=new Date(); now.setHours(12,0,0,0); const start=iso(c.start_date),end=iso(c.end_date);
    if(!start||!end)return{configured:false,weeksDone:0,weeksLeft:null,pct:0,length:0,status:'DATES REQUIRED'};
    const length=Math.max(1,Math.ceil((end-start)/day/7));
    const weeksDone=Math.max(0,Math.min(length,Math.floor((now-start)/day/7)));
    const weeksLeft=Math.ceil((end-now)/day/7); const pct=Math.max(0,Math.min(100,Math.round((now-start)/(end-start)*100)));
    const m=c.metadata||{}; let status='NOT DUE';
    if(m.continuation_status==='renewed')status='RENEWED';
    else if(weeksLeft<=4&&m.continuation_status!=='discussed')status='RETENTION ACTION REQUIRED';
    else if(weeksLeft<=6)status='RETENTION WINDOW OPEN';
    else if(pct>=50&&!m.referral_asked&&m.referral_status!=='skip')status='REFERRAL REVIEW';
    return{configured:true,weeksDone,weeksLeft,pct,length,status};
  }
  async function load(){
    if(!USE_SUPABASE){state.ready=true;return;}
    try{
      const [clients,refs]=await Promise.all([
        sbFetch('tle_clients',{select:'*',filters:['order=status.asc','limit=500']}),
        sbFetch('tle_client_referrals',{select:'*',filters:['order=created_at.desc','limit=1000']})
      ]);
      state.clients=Array.isArray(clients)?clients:[]; state.referrals=Array.isArray(refs)?refs:[]; state.ready=true;
      await ensureTasks(); updateBadge();
    }catch(e){console.error(e);state.ready=true;toast('Client lifecycle could not sync');}
  }
  function updateBadge(){const n=state.clients.filter(c=>{const x=calc(c);return x.status==='RETENTION ACTION REQUIRED'||x.status==='REFERRAL REVIEW'||!x.configured}).length;const b=document.getElementById('badge-lifecycle');if(b){b.textContent=n;b.style.display=n?'':'none';}}
  async function ensureTasks(){
    const tasks=DB.tasks.slice(); let changed=false;
    const add=(c,type,title,due,priority='Normal')=>{const id=`lifecycle:${c.id}:${type}`;if(tasks.some(t=>String(t.lifecycleEventId)===id))return;tasks.push({id:Date.now()+tasks.length,lifecycleEventId:id,clientId:c.id,leadId:c.lead_id,title,due:due||new Date().toISOString().slice(0,10),priority,status:'Open',created:new Date().toISOString(),source:'Client Lifecycle'});changed=true;};
    state.clients.filter(c=>c.status==='active').forEach(c=>{const x=calc(c),m=c.metadata||{},name=leadFor(c).name||'Client';if(!x.configured)add(c,'dates',`Add programme dates for ${name}`,null,'High');else if(x.status==='REFERRAL REVIEW')add(c,'referral-50',`Review ${name} for referral opportunity`);else if(x.status==='RETENTION ACTION REQUIRED')add(c,'retention-4w',`Continuation conversation must happen with ${name}`,null,'Urgent');else if(x.status==='RETENTION WINDOW OPEN'&&m.continuation_status!=='discussed')add(c,'retention-6w',`Open continuation conversation with ${name} on next coaching call`,null,'High');if(x.configured&&x.weeksLeft<=2&&x.weeksLeft>1&&!m.continuation_next_date)add(c,'retention-2w',`Resolve continuation plan with ${name}`,null,'Urgent');if(x.configured&&x.weeksLeft<=1&&x.weeksLeft>=0&&!m.continuation_next_date)add(c,'retention-7d',`${name}'s programme ends within 7 days`,null,'Urgent');});
    if(changed)DB.tasks=tasks;
  }
  function metrics(){const active=state.clients.filter(c=>c.status==='active'),eligible=active.filter(c=>calc(c).status==='REFERRAL REVIEW').length,converted=state.referrals.filter(r=>r.converted).length,due=active.filter(c=>['RETENTION WINDOW OPEN','RETENTION ACTION REQUIRED'].includes(calc(c).status)).length,month=new Date().toISOString().slice(0,7),renewed=active.filter(c=>(c.renewal_date||'').startsWith(month)).length,ending=active.filter(c=>{const x=calc(c);return x.configured&&x.weeksLeft>=0&&x.weeksLeft<=4}).length;const ended=state.clients.filter(c=>['past','cancelled'].includes(c.status)).length;const rate=(renewed+ended)?Math.round(renewed/(renewed+ended)*100):0;return{active:active.length,eligible,refs:state.referrals.length,converted,due,renewed,ending,rate};}
  function actionRows(){return state.clients.map(c=>({c,x:calc(c),l:leadFor(c)})).filter(o=>o.c.status==='active'&&(!o.x.configured||o.x.status!=='NOT DUE')).sort((a,b)=>{const rank={'RETENTION ACTION REQUIRED':0,'DATES REQUIRED':1,'RETENTION WINDOW OPEN':2,'REFERRAL REVIEW':3,'RENEWED':4};return (rank[a.x.status]??9)-(rank[b.x.status]??9)}).map(({c,x,l})=>{let desc=!x.configured?'Programme dates missing — timeline cannot run':x.status==='REFERRAL REVIEW'?`${x.pct}% complete — review meaningful result before asking`:x.status==='RETENTION ACTION REQUIRED'?`${Math.max(0,x.weeksLeft)} weeks remaining — continuation not resolved`:x.status==='RETENTION WINDOW OPEN'?`${x.weeksLeft} weeks remaining — add continuation to next call`:'Renewed';let cls=x.status==='RETENTION ACTION REQUIRED'?'lc-red':!x.configured?'lc-orange':x.status==='REFERRAL REVIEW'?'lc-yellow':'lc-green';return`<div class="lc-action"><span class="lc-dot ${cls}"></span><div><div class="lc-action-name">${esc(l.name||'Unnamed client')}</div><div class="lc-sub">${esc(desc)}</div></div><button class="btn btn-ghost btn-sm" onclick="Lifecycle.open(${c.id})">Review</button></div>`}).join('');}
  function render(){const root=document.getElementById('lifecycle-root');if(!root)return;if(!state.ready){root.innerHTML='<div class="lc-empty">Loading live client lifecycle…</div>';load().then(render);return;}const m=metrics();root.innerHTML=`<div class="lc-grid">${[['Active clients',m.active],['Referral opportunities',m.eligible],['Referrals generated',m.refs],['Referrals converted',m.converted],['Retention due',m.due],['Renewals this month',m.renewed],['Ending in 30 days',m.ending],['Renewal rate',m.rate+'%']].map(([a,b])=>`<div class="lc-card"><div class="lc-kicker">${a}</div><div class="lc-number">${b}</div></div>`).join('')}</div><div class="lc-panel"><div class="lc-panel-h"><h3>Action required</h3><span class="lc-pill">Urgent first</span></div>${actionRows()||'<div class="lc-empty">No lifecycle actions are due.</div>'}</div><div class="lc-panel"><div class="lc-panel-h"><h3>Clients</h3><span class="lc-sub">Timelines calculate automatically from programme dates</span></div><div style="overflow:auto"><table class="lc-table"><thead><tr><th>Client</th><th>Programme</th><th>Progress</th><th>Remaining</th><th>Referral</th><th>Retention</th></tr></thead><tbody>${state.clients.map(c=>{const l=leadFor(c),x=calc(c),meta=c.metadata||{};return`<tr><td><span class="lc-link" onclick="Lifecycle.open(${c.id})">${esc(l.name||'Unnamed')}</span><div class="lc-sub">${esc(c.status)}</div></td><td>${fmt(c.start_date)} → ${fmt(c.end_date)}</td><td style="min-width:170px">${x.configured?`Week ${x.weeksDone} of ${x.length} · ${x.pct}%<div class="lc-progress"><span style="width:${x.pct}%"></span></div>`:'Dates required'}</td><td>${x.configured?Math.max(0,x.weeksLeft)+' weeks':'—'}</td><td>${esc(meta.referral_status||'Not reviewed')}</td><td><span class="lc-pill ${x.status.includes('ACTION')?'danger':x.status.includes('WINDOW')?'warn':x.status==='RENEWED'?'good':''}">${x.status}</span></td></tr>`}).join('')}</tbody></table></div></div><div class="lc-modal" id="lc-modal" onclick="if(event.target===this)Lifecycle.close()"><div class="lc-dialog" id="lc-dialog"></div></div>`;updateBadge();}
  function open(id){const c=state.clients.find(x=>String(x.id)===String(id));if(!c)return;const l=leadFor(c),x=calc(c),m=c.metadata||{},dialog=document.getElementById('lc-dialog');const steps=['Onboarded','25% complete','50% referral','6 weeks left','4 weeks left','Discussed','Renewed / finished'];let active=!x.configured?0:x.status==='REFERRAL REVIEW'?2:x.status==='RETENTION WINDOW OPEN'?3:x.status==='RETENTION ACTION REQUIRED'?4:m.continuation_status==='discussed'?5:m.continuation_status==='renewed'?6:(x.pct>=25?1:0);dialog.innerHTML=`<div class="lc-dialog-h"><div><strong>${esc(l.name||'Client')}</strong><div class="lc-sub">${x.configured?`Week ${x.weeksDone} of ${x.length} · ${x.pct}% complete · ${Math.max(0,x.weeksLeft)} weeks remaining`:'Add programme dates to activate the lifecycle'}</div></div><button class="btn btn-ghost btn-sm" onclick="Lifecycle.close()">✕</button></div><div class="lc-dialog-b"><div class="lc-timeline">${steps.map((s,i)=>`${i?'<span class="lc-arrow">›</span>':''}<span class="lc-step ${i===active?'active':''}">${s}</span>`).join('')}</div><div class="lc-form"><div><label>Programme start</label><input id="lc-start" type="date" value="${esc(c.start_date||'')}"></div><div><label>Programme end</label><input id="lc-end" type="date" value="${esc(c.end_date||'')}"></div><div><label>Next coaching call</label><input id="lc-next-call" type="datetime-local" value="${esc((m.next_coaching_call||'').slice(0,16))}"></div><div><label>Programme</label><input id="lc-programme" value="${esc(c.programme||'')}"></div><div class="full"><label>Recent meaningful result</label><textarea id="lc-result">${esc(m.result_referenced||'')}</textarea></div></div>${x.pct>=50&&!m.referral_asked?`<div class="lc-callout"><strong>Referral opportunity</strong><div class="lc-sub">Has this client achieved a meaningful result worth referencing?</div><div class="lc-actions"><button class="btn btn-primary btn-sm" onclick="Lifecycle.referral(${c.id},'eligible')">Yes — eligible</button><button class="btn btn-ghost btn-sm" onclick="Lifecycle.referral(${c.id},'later')">Review in 2 weeks</button><button class="btn btn-ghost btn-sm" onclick="Lifecycle.referral(${c.id},'skip')">Skip</button></div></div>`:''}${x.configured&&x.weeksLeft<=6?`<div class="lc-callout retention"><strong>Continuation conversation</strong><div class="lc-sub">Programme ends ${fmt(c.end_date)} · ${Math.max(0,x.weeksLeft)} weeks remaining</div><div class="lc-actions">${['Interested','Maybe / discuss later','Plans to finish','Renewed'].map(v=>`<button class="btn btn-ghost btn-sm" onclick="Lifecycle.continuation(${c.id},'${v.toLowerCase().split(' ')[0]}')">${v}</button>`).join('')}</div></div>`:''}<div class="lc-actions"><button class="btn btn-primary" onclick="Lifecycle.save(${c.id})">Save client timeline</button><button class="btn btn-ghost" onclick="Lifecycle.createReferral(${c.id})">＋ Add referral</button></div></div>`;document.getElementById('lc-modal').classList.add('open');}
  function close(){const m=document.getElementById('lc-modal');if(m)m.classList.remove('open');}
  async function save(id,metaPatch={}){const c=state.clients.find(x=>String(x.id)===String(id));if(!c)return;const start=document.getElementById('lc-start'),end=document.getElementById('lc-end'),program=document.getElementById('lc-programme'),call=document.getElementById('lc-next-call');const updated={...c,start_date:start?start.value:c.start_date,end_date:end?end.value:c.end_date,programme:program?program.value:c.programme,metadata:{...(c.metadata||{}),...(call?{next_coaching_call:call.value}:{}),result_referenced:document.getElementById('lc-result')?.value||c.metadata?.result_referenced||'',...metaPatch},updated_at:new Date().toISOString()};await sbFetch('tle_clients',{method:'PATCH',body:updated,filters:[`id=eq.${id}`]});Object.assign(c,updated);await ensureTasks();toast('Client lifecycle saved');close();render();}
  async function referral(id,status){const patch=status==='eligible'?{referral_status:'eligible',referral_eligible:true}:status==='later'?{referral_status:'review later',referral_review_at:new Date(Date.now()+14*day).toISOString().slice(0,10)}:{referral_status:'skip'};await save(id,patch);}
  async function continuation(id,status){const patch={continuation_status:status,continuation_discussed_at:new Date().toISOString()};if(status==='maybe'){const d=prompt('Follow-up date (YYYY-MM-DD)');if(!d)return;patch.continuation_next_date=d;}await save(id,patch);}
  async function createReferral(id){const c=state.clients.find(x=>String(x.id)===String(id));const name=prompt('Referral name');if(!name)return;const row={client_id:id,referral_name:name,referral_date:new Date().toISOString().slice(0,10),status:'lead received',converted:false,reward_delivered:false,metadata:{}};await sbFetch('tle_client_referrals',{method:'POST',body:row});toast('Referral recorded');close();await load();render();}
  window.Lifecycle={render,open,close,save,referral,continuation,createReferral,load};
  window.addEventListener('load',()=>load());
})();
