create table if not exists public.tle_client_referrals (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.tle_clients(id) on delete cascade,
  referral_lead_id bigint references public.tle_leads(id) on delete set null,
  referral_name text not null,
  referral_date date not null default current_date,
  status text not null default 'potential',
  converted boolean not null default false,
  converted_at timestamptz,
  reward_type text,
  reward_due boolean not null default false,
  reward_delivered boolean not null default false,
  reward_delivered_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.tle_client_referrals enable row level security;

insert into public.tle_clients (lead_id,status,contract_value,currency,metadata)
select l.id,
       case when lower(coalesce(l.data->>'status','')) like '%inactive%' then 'past' else 'active' end,
       nullif(regexp_replace(coalesce(l.data->>'dealValue',''),'[^0-9.]','','g'),'')::numeric,
       coalesce(nullif(l.data->>'currency',''),'EUR'),
       jsonb_build_object('lifecycle_imported_at',now(),'dates_required',true)
from public.tle_leads l
where lower(coalesce(l.data->>'stage',''))='won'
   or lower(coalesce(l.data->>'status','')) in ('won','client','active client')
on conflict (lead_id) do nothing;

drop policy if exists "crm client lifecycle access" on public.tle_clients;
create policy "crm client lifecycle access" on public.tle_clients
for all to anon using (true) with check (true);

drop policy if exists "crm referral lifecycle access" on public.tle_client_referrals;
create policy "crm referral lifecycle access" on public.tle_client_referrals
for all to anon using (true) with check (true);

grant select, insert, update, delete on public.tle_clients to anon;
grant select, insert, update, delete on public.tle_client_referrals to anon;
grant usage, select on sequence public.tle_clients_id_seq to anon;
grant usage, select on sequence public.tle_client_referrals_id_seq to anon;
